name: Build and Deploy

on:
  push:
    branches:
      - release

env:
  SERVICE_NAME: chat-bot
  NAMESPACE: chat-bot

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set datetime and image
        id: set-datetime
        run: |
          DATETIME=$(date +'%Y%m%d-%H%M%S')
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          IMAGE_TAG="${{ env.SERVICE_NAME }}:${DATETIME}-${SHORT_SHA}"
          FULL_IMAGE="${{ secrets.REGISTRY_HOST }}/${IMAGE_TAG}"
          
          echo "DATETIME=$DATETIME" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "FULL_IMAGE=$FULL_IMAGE" >> $GITHUB_ENV
          
          echo "Generated image tag: $IMAGE_TAG"
          echo "Full image path: $FULL_IMAGE"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.REGISTRY_HOST }}/${{ env.SERVICE_NAME }}:latest
            ${{ env.FULL_IMAGE }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes access
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify access and image info
        run: |
          echo "Проверяем доступ к namespace ${{ env.NAMESPACE }}"
          kubectl auth can-i patch deployments -n ${{ env.NAMESPACE }}
          kubectl get deployments -n ${{ env.NAMESPACE }}
          echo ""
          echo "Image info:"
          echo "SERVICE_NAME: ${{ env.SERVICE_NAME }}"
          echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"
          echo "FULL_IMAGE: ${{ env.FULL_IMAGE }}"

      - name: Get current deployment revision
        id: get-old-rev
        run: |
          rev=$(kubectl get deployment ${{ env.SERVICE_NAME }} -n ${{ env.NAMESPACE }} -o jsonpath='{.metadata.annotations.deployment\.kubernetes\.io/revision}' 2>/dev/null || echo "")
          echo "old_rev=$rev" >> $GITHUB_OUTPUT
          echo "Current revision: $rev"

      - name: Deploy new image
        run: |
          echo "Deploying image: ${{ env.FULL_IMAGE }}"
          kubectl set image deployment/${{ env.SERVICE_NAME }} ${{ env.SERVICE_NAME }}=${{ env.FULL_IMAGE }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/${{ env.SERVICE_NAME }} -n ${{ env.NAMESPACE }} --timeout=60s

      - name: Rollback if failed
        if: failure()
        run: |
          if [ -z "${{ steps.get-old-rev.outputs.old_rev }}" ]; then
            echo "ERROR: Cannot rollback - no previous revision found"
            echo "This might be the first deployment"
            exit 1
          fi
          echo "Rolling back to revision ${{ steps.get-old-rev.outputs.old_rev }}"
          kubectl rollout undo deployment/${{ env.SERVICE_NAME }} -n ${{ env.NAMESPACE }} --to-revision=${{ steps.get-old-rev.outputs.old_rev }}
          kubectl rollout status deployment/${{ env.SERVICE_NAME }} -n ${{ env.NAMESPACE }} --timeout=60s
          echo "ERROR: Deployment failed, rolled back to revision ${{ steps.get-old-rev.outputs.old_rev }}"
          exit 1

      - name: Deployment success
        run: |
          echo "🎉 Deployment successful!"
          kubectl get deployment ${{ env.SERVICE_NAME }} -n ${{ env.NAMESPACE }}
          echo "New image: ${{ env.FULL_IMAGE }}"